package com.ecristobale.bookapi.models

import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Positive

@Entity
data class Book(
    @Id // PK
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates IDs
    val id: Long? = null, // Nullable because it's generated by DB

    // @field: prefix is necessary for validation annotations in Kotlin to target the field rather than the constructor parameter
    @field:NotBlank(message = "Title is required") // Validation rule
    val title: String, // Non-nullable String - must always have a value


    @field:NotBlank(message = "Author is required")
    val author: String,

    @field:Positive(message = "Publish year must be positive")
    val publishYear: Int
)